---
title: "Cessão de Espaço Aquático"
subtitle: "Golar Power Latam Participações e Comércio Ltda."
author: "Luiz Fernando Palin Droubi"
date: "`r format(Sys.Date(), '%d/%m/%Y')`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, fig.align = "center", out.width = "100%")
library(RPostgreSQL)
library(rpostgis)
library(sp)
```

## Conectar ao Banco de Dados Espacial

```{r}
conn <- dbConnect("PostgreSQL",
                  host = "localhost", 
                  dbname = "spugeo",
                  user = "postgres", 
                  password = "campeao1")
```

## Verificar que o Banco de Dados é Espacial

```{r}
pgPostGIS(conn)
```


## Listar objetos constantes do BDE

```{r}
# Objetos Vetoriais
pgListGeom(conn)
#Objetos Raster
pgListRast(conn)
```

## Criar objeto

```{r}
# 1. Digitação da Geometria
#  
# Digitar Coordenadas dos vértices
#
#                             E             N
coords <- matrix(data = c(742739.4319, 7102378.0901, #1
                          743689.4419, 7103579.0401, #2
                          744102.8256, 7103252.0335, #3
                          743152.8156, 7102051.0835, #4
                          742739.4319, 7102378.0901),#1
                 ncol = 2, byrow = TRUE)
#
# 2. Criação da feição  
#
# Atentar para a definição do crs apropriado
# 
#
# Exemplos:
# WGS 84 = 4326
# SAD 69 22S = 29192
# SIRGAS 2000 22S = 31982
#
pl <- Polygon(coords)
spl <- SpatialPolygons(list(Polygons(list(pl), ID = 1)),
                      proj4string = CRS("+init=epsg:31982")) 
#
# 3. Criação dos metadados  
#
dados <- data.frame(interessado = "Golar Power Latam Participações e Comércio Ltda",
                    cnpj = "24.360.766/0001-45",
                    protocolo = "SC04142/2018",
                    nup = "04972.010861/2018-05",
                    ref = 7881639,
                    onerosa = TRUE,
                    concedida = FALSE,
                    area = pl@area,
                    municipio = 8319,
                    logradouro = "08-00",
                    aval = NA,
                    dataaval = NA)
spl_df <- SpatialPolygonsDataFrame(spl, dados)
```

## 4. Escrever a nova entrada no BDE

```{r}
pgInsert(conn = conn, name = c(schema="espacoaquatico", table = "cessao"), data.obj = spl_df)
```




## Disconectar do BDE

```{r}
dbDisconnect(conn)
```

