---
title: "Porto de SFS"
subtitle: "Poligonal atualizada em 05/07/2019"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE)

library(sf)
library(leaflet)
```

## Criar objeto

```{r}
#
# 1 Criação da poligonal do porto
#
#  
# 1.1 Leitura das poligonais em KML
#  
anexo_i <- st_read("imbituba/poligonal_2019.kml", layer = "Anexo I") %>% st_zm()
anexo_ii <- st_read("imbituba/poligonal_2019.kml", layer = "Anexo II") %>% st_zm()
anexo_iii <- st_read("imbituba/poligonal_2019.kml", layer = "Anexo III") %>% st_zm()
#
# 1.2 Junção dos polígonos
pl <- st_sfc(st_multipolygon(
  list(list(st_coordinates(anexo_i)), 
       list(st_coordinates(anexo_ii)),
       list(st_coordinates(anexo_iii)))
  )
  )
#
spl <- st_sf(pl, crs = 4326)
#
# 2. Criação dos atributos  
#
attr <- data.frame(descricao = "Área do Porto Organizado de Imbituba",
                   area = st_area(st_transform(spl, 31982)),
                   municipio = 8143,
                   portaria = 557,
                   data = as.Date("27/09/2019", format = "%d/%m/%Y"),
                   fonte = "http://infraestrutura.gov.br/images/arquivos-poligonais-das-areas-dos-portos-organizados/imbituba.zip",
                   data_acesso = as.Date("30/01/2020", format = "%d/%m/%Y")
                   )
#
# 4. União dos atributos à geometria
#
spl_df <- st_sf(attr,
                geometry= pl,
                crs = 4326)
```

## Exportar

```{r}
# 5. Escrever a nova entrada no BDE
#
st_write(spl_df, "imbituba.geojson", delete_dsn = TRUE)
```
