---
title: "Porto de Laguna"
subtitle: "Poligonal atualizada em 05/07/2019"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE)
library(RPostgreSQL)
library(rpostgis)
library(sf)
library(leaflet)
```

## Conectar ao Banco de Dados Espacial

```{r, echo=FALSE}
conn <- dbConnect("PostgreSQL",
                  host = "localhost", 
                  dbname = "spugeo",
                  user = "postgres", 
                  password = "campeao1")
```

## Criar objeto

```{r}
#
# 1 Criação da poligonal do porto
#
# 1.1 Leitura da poligonal em KML
# Obs.: Da poliganal abaixo são extraídos pontos dos vértices. 
# É necessário confeccionar manualmente o polígono.
#  
pts <- st_read("laguna/poligonal_atual.kml")
#
# 1.2 Extração das coordenadas
#
coords <- st_zm(st_coordinates(pts))
#
# 1.3 Adicionar a primeira coordenada ao final da matriz de coordenadas.
coords <- rbind(coords, coords[1,])
#
# 1.4 Criar o polígono
#
pl <- st_polygon(list(coords))
#
# 1.5 Criar feição
#
pl <- st_sfc(pl, crs = 4326)
#
# 2. Criação dos atributos  
#
attr <- data.frame(descricao = "Área do Porto Organizado de Laguna",
                   area = st_area(pl),
                   municipio = 8185,
                   portaria = 1008,
                   data = as.Date("16/12/1993", format = "%d/%m/%Y"),
                   fonte = "http://infraestrutura.gov.br/images/arquivos-poligonais-das-areas-dos-portos-organizados/copy_of_laguna.zip",
                   data_acesso = as.Date("11/09/2019", format = "%d/%m/%Y")
                   )
#
# 4. União dos atributos à geometria
#
spl_df <- st_sf(attr,
                geom = pl)
```

## Exportar

```{r}
# 5. Escrever a nova entrada no BDE
#
st_write(spl_df, "laguna.geojson", delete_dsn = TRUE)
```
